services:
  - docker

env:
  global:
    # The following secret must be set
    # DOCKER_PASS
    - DOCKER_USER=russellhoff
    - REPO=russellhoff/gdal-base  # Dockerhub repository name, not github
    - COMMIT=${TRAVIS_COMMIT::8}
    - DATE=`date +%Y%m%d`
    - TAG="$DATE-$COMMIT"

install:
    - travis_wait 49 make

script:
    - make test

deploy:
  provider: script
  script: bash docker-push.sh
  on:
      branch: master
